# Generated by Django 4.0.4 on 2022-05-20 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=10)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('during_time', models.DurationField()),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('Боевик', 'Боевик'), ('Комедия', 'Комедия'), ('Приключения', 'Приключения'), ('Мультфильм', 'Мультфильм'), ('Ужасы', 'Ужасы'), ('Спорт', 'Спорт'), ('Фантастика', 'Фантастика'), ('Фэнтези', 'Фэнтези'), ('Триллер', 'Триллер'), ('Детектив', 'Детектив'), ('История', 'История'), ('Документальный фильм', 'Документальный фильм'), ('Семейный', 'Семейный'), ('Драма', 'Драма')], max_length=129)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RowOfHall',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.rowofhall')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_dis', models.FloatField()),
                ('total_price', models.FloatField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.discount')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.seat')),
                ('shed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
