# Generated by Django 4.0.4 on 2022-05-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0002_payment_remove_reservation_price_dis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.FileField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
