# Generated by Django 4.0.4 on 2022-05-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_reservation_payment_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.FileField(default=1, upload_to='doc'),
        ),
    ]
