# Generated by Django 4.0.4 on 2022-05-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_reservation_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
    ]
