# Generated by Django 4.0.4 on 2022-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_remove_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.ImageField(default=1, upload_to='movie'),
        ),
    ]
