# Generated by Django 4.0.4 on 2022-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_alter_reservation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
